/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.club;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Produit extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public Produit() {
        super("Produits");
        initComponents();
        conn = DBConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        b_menu_clubs = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_pro_id = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_pro = new javax.swing.JTable();
        b_aj_pro = new javax.swing.JButton();
        b_mod_pro = new javax.swing.JButton();
        b_supp_pro = new javax.swing.JButton();
        b_rech_pro = new javax.swing.JButton();
        txt_rech_pro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_pro_cne = new javax.swing.JTextField();
        b_aff_pro = new javax.swing.JButton();
        txt_pro_nom = new javax.swing.JTextField();
        txt_pro_prix = new javax.swing.JTextField();
        txt_pro_q = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 204, 0));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Menu");

        b_menu_clubs.setBackground(new java.awt.Color(0, 255, 51));
        b_menu_clubs.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        b_menu_clubs.setForeground(new java.awt.Color(255, 255, 255));
        b_menu_clubs.setText("Clients");
        b_menu_clubs.setBorder(null);
        b_menu_clubs.setBorderPainted(false);
        b_menu_clubs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b_menu_clubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_menu_clubsActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(0, 255, 51));
        jButton22.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Produits");
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(0, 255, 51));
        jButton23.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("Employees");
        jButton23.setBorder(null);
        jButton23.setBorderPainted(false);
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(255, 51, 51));
        jButton24.setText("Logout");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b_menu_clubs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jButton24))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(b_menu_clubs, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton24)
                .addGap(0, 136, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setText("ID :");

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setText("Nom de Produit :");

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setText("Prix de Produit :");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel10.setText("Quntite du Produit :");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel11.setText("Gestion Des Produits");

        tab_pro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom de Produits", "Prix", "Quantite", "CNE de L'employee"
            }
        ));
        tab_pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_proMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab_pro);

        b_aj_pro.setText("Ajouter");
        b_aj_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aj_proActionPerformed(evt);
            }
        });

        b_mod_pro.setText("Modifier");
        b_mod_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_mod_proActionPerformed(evt);
            }
        });

        b_supp_pro.setText("Supprimer");
        b_supp_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_supp_proActionPerformed(evt);
            }
        });

        b_rech_pro.setText("Rechercher");
        b_rech_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_rech_proActionPerformed(evt);
            }
        });

        txt_rech_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rech_proActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel12.setText("CNE Employees : ");

        txt_pro_cne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pro_cneActionPerformed(evt);
            }
        });

        b_aff_pro.setText("Afficher");
        b_aff_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aff_proActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(b_aff_pro)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txt_rech_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(b_rech_pro))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGap(52, 52, 52)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_pro_id, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_pro_cne, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_pro_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_pro_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_pro_q, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(221, 221, 221))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(b_aj_pro)
                                .addGap(18, 18, 18)
                                .addComponent(b_mod_pro)
                                .addGap(18, 18, 18)
                                .addComponent(b_supp_pro)
                                .addGap(67, 67, 67))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel11)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel11)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_pro_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_pro_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_pro_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_pro_q, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_pro_cne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_aj_pro)
                    .addComponent(b_mod_pro)
                    .addComponent(b_supp_pro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_rech_pro)
                    .addComponent(txt_rech_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(b_aff_pro)
                        .addGap(96, 96, 96))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pro_cneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pro_cneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pro_cneActionPerformed

    private void txt_rech_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rech_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rech_proActionPerformed

    private void b_mod_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_mod_proActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:

        try {
            int id = Integer.parseInt(txt_pro_id.getText());
            String nom = txt_pro_nom.getText();
            int prix = Integer.parseInt(txt_pro_prix.getText());
            int q = Integer.parseInt(txt_pro_q.getText());
            int cne = Integer.parseInt(txt_pro_cne.getText());
            PreparedStatement ps = conn.prepareStatement("update produits set id_prod="+id+" , nom_prod='"+nom+"' , prix_prod='"+prix+"' , quantite_prod= '"+q+"' ,  cne_emp= "+cne+" where id_prod = "+id+"");
            int i = ps.executeUpdate();
            
            if (i>0){
                  JOptionPane.showMessageDialog(null,"Modification Valide !!");
        }

            }
            catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
    }//GEN-LAST:event_b_mod_proActionPerformed

        private void modifier() throws SQLException{
        String sql= "select * from produits";
        
        PreparedStatement p = conn.prepareStatement(sql);
        try{
            p = conn.prepareStatement(sql);
            rs = p.executeQuery();
            tab_pro.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e); 
        }
    }
    
    private void b_aj_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aj_proActionPerformed

            try {
                int id = Integer.parseInt(txt_pro_id.getText());
                String nom = txt_pro_nom.getText();
                int prix = Integer.parseInt(txt_pro_prix.getText());
                int q = Integer.parseInt(txt_pro_q.getText());
                int cne = Integer.parseInt(txt_pro_cne.getText());
           
                PreparedStatement p = conn.prepareStatement("INSERT INTO produits VALUES('"+id+"','"+nom+"','"+prix+"','"+q+"','"+cne+"')");
                //PreparedStatement p = conn.prepareStatement("call addItemProduit('"+num+"','"+type+"','"+tai+"','"+col+"','"+prix+"')");
                
                p.execute();
                JOptionPane.showMessageDialog(null,"Le produit a été bien insere");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
    }//GEN-LAST:event_b_aj_proActionPerformed

    private void tab_proMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_proMouseClicked
        
          try {
        int row = tab_pro.getSelectedRow();
        String tab_click = (tab_pro.getModel().getValueAt(row,0).toString());
        String sql = "select * from produits where id_prod ='"+tab_click+"'";
  
       PreparedStatement  ps = conn.prepareStatement(sql);
            rs= ps.executeQuery();
             
            if(rs.next()){
                String add1 = rs.getString("ID_PROD");
                txt_pro_id.setText(add1);
                String add2 = rs.getString("NOM_PROD");
                txt_pro_nom.setText(add2);
                String add3 = rs.getString("PRIX_PROD");
                txt_pro_prix.setText(add3);
                String add4 = rs.getString("QUANTITE_PROD");
                txt_pro_q.setText(add4);
                String add5 = rs.getString("CNE_EMP");
                txt_pro_cne.setText(add5);
                
            }
            

        } catch (SQLException ex) {
            Logger.getLogger(Clients.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tab_proMouseClicked

    private void b_menu_clubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_menu_clubsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Clients obj = new Clients();
        obj.setVisible(true);
  
    }//GEN-LAST:event_b_menu_clubsActionPerformed

    private void b_supp_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_supp_proActionPerformed
                        try {
        int row = tab_pro.getSelectedRow();
        String x = tab_pro.getModel().getValueAt(row,0).toString();
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Vous voulez vraiment le supprimer ?");
        if(dialogResult == 0) {
        String sql ="DELETE FROM produits WHERE id_prod ='"+x+"'";
        PreparedStatement  ps = conn.prepareStatement(sql);
        // PreparedStatement  ps = conn.prepareStatement("call deleteItemProduit('"+x+"')");
         ps.executeUpdate();
         JOptionPane.showMessageDialog(null,"Suppression Valide !!");
        
         modifier();
         
         txt_pro_id.setText(null);
         txt_pro_nom.setText(null);
         txt_pro_prix.setText(null);
         txt_pro_q.setText(null);
         txt_pro_cne.setText(null);

         
        }
       
            
        } catch (SQLException ex) {
            Logger.getLogger(Clients.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_b_supp_proActionPerformed

    private void b_rech_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_rech_proActionPerformed
        // TODO add your handling code here:
        int id_prod = Integer.parseInt(txt_rech_pro.getText()) ;
        for(int i = 0 ; i<tab_pro.getRowCount() ; i++) {
          if(tab_pro.getValueAt(i,0).equals(id_prod)){
              tab_pro.setRowSelectionInterval(i,i);
          }
      }

    }//GEN-LAST:event_b_rech_proActionPerformed

    private void b_aff_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aff_proActionPerformed
        // TODO add your handling code here:
            try {
            PreparedStatement ps = conn.prepareStatement("select * from produits");
            rs = ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)tab_pro.getModel();
            tm.setRowCount(0);
            
            while(rs.next()){
                Object o[]={rs.getInt("ID_PROD"),rs.getString("NOM_PROD"),rs.getInt("PRIX_PROD"),rs.getInt("QUANTITE_PROD"),rs.getInt("CNE_EMP")};
                tm.addRow(o);
                        
                }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Clients.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_aff_proActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
                        setVisible(false);
        Employees obj = new Employees();
        obj.setVisible(true); 
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
                               setVisible(false);
        Produit obj = new Produit();
        obj.setVisible(true); 
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
                setVisible(false);
        login obj = new login();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_aff_pro;
    private javax.swing.JButton b_aj_pro;
    private javax.swing.JButton b_menu_clubs;
    private javax.swing.JButton b_mod_pro;
    private javax.swing.JButton b_rech_pro;
    private javax.swing.JButton b_supp_pro;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tab_pro;
    private javax.swing.JTextField txt_pro_cne;
    private javax.swing.JTextField txt_pro_id;
    private javax.swing.JTextField txt_pro_nom;
    private javax.swing.JTextField txt_pro_prix;
    private javax.swing.JTextField txt_pro_q;
    private javax.swing.JTextField txt_rech_pro;
    // End of variables declaration//GEN-END:variables
}
